### PR TITLE
Slider label bug fix

### LINKED ISSUE #40: setupSliderLabel seems to be scaling improperly when marked as horizontal text
See current master to see scaling the page seems to move the 'Octave' text around.

@KyleNehman could you look into this?

### PR DESCRIPTION
**Pull request by KyleNehman**
#40

Modified horizontal slider labels so that they now appear centered underneath of the slider. Maybe add an optional arg for on top of or left/right of? 

Vertical slider labels have had their multiplier changed from 1.5 \* height, which caused obvious spacing issues, to approx height / 2 \* .123 (half of the height of the slider itself)

### CODE REVIEW

File: sketch.js [hunk 1]
```diff
@@ -57,6 +58,10 @@ function setupSliders() {
   setupSliderLabel(xTranslateSliders + (17 * sliderSpacer), sliderHeight, true, 'TRI');
   subSlider = setupSlider(xTranslateSliders + (18 * sliderSpacer), sliderHeight, 256, 0, true);
   setupSliderLabel(xTranslateSliders + (18 * sliderSpacer), sliderHeight, true, 'SUB');
+
+//  rect(200, 0, 20, 0);
+
+
```
Comment (JoshuaStorm) [inline sketch.js]: ~~What's up with this extra white space and comment?~~

Oops looked at wrong commit

**Comment by JoshuaStorm** [comment]
@KyleNehman Thanks!
